- name: Automatic Releases
  uses: marvinpinto/action-automatic-releases@v1.2.1
  
  ---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
       - name: Test with dotnet
         working-directory: ./src/Spice86.Tests
         run: dotnet test --configuration Release

       - name: Build with dotnet
         working-directory: ./src/Spice86.AvaloniaUI
         run: dotnet build --configuration Release

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: ./src/Spice86.AvaloniaUI/bin/Release/*
