name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
       - uses: actions/checkout@v1

       - name: Setup .NET
         uses: actions/setup-dotnet@v1
         with:
           dotnet-version: '7.0.x'

       - name: Install zip
         uses: montudor/action-zip@v1

       - name: Test with dotnet
         working-directory: ./src/Spice86.Tests
         run: dotnet test --configuration Release

       - name: Build with dotnet
         working-directory: ./src/Spice86
         run: |
              dotnet restore
              dotnet publish --no-restore -c Release -r linux-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o Release/linux
              dotnet publish --no-restore -c Release -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o Release/windows
              dotnet publish --no-restore -c Release -r osx-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o Release/macos
              dotnet publish --no-restore -c Debug -r linux-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o Debug/linux
              dotnet publish --no-restore -c Debug -r win-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o Debug/windows
              dotnet publish --no-restore -c Debug -r osx-x64 --self-contained true -p:PublishReadyToRun=true -p:PublishSingleFile=true -o Debug/macos

       - name: Zip output
         run: zip -qq -r Release.zip Release
         working-directory: ./src/Spice86/bin

       - name: Publish GitHub Release
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
           automatic_release_tag: "latest"
           prerelease: true
           title: "Development Build"
           files: |
             ./src/Spice86/bin/Release.zip
