name: .NET Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Test with dotnet
      working-directory: ./src
      run: dotnet test --configuration Release

    - name: Package NuGet
      working-directory: ./src
      run: dotnet pack --include-symbols --include-source --configuration Release -o .

    - name: Upload NuGet
      working-directory: ./src
      run: nuget push *.nupkg ${{secrets.NUGET_API_KEY}} -Source 'https://api.nuget.org/v3/index.json' -SkipDuplicate

