name: .NET Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release src/Spice86/Spice86.sln
      
    - name: Test with dotnet
      run: dotnet test --configuration Release src/Spice86/Spice86.sln

    - name: Package NuGet
      run: dotnet pack src/Spice86/Spice86.csproj --configuration Release

    - name: Upload NuGet
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NuGet Package
        path: nupkg
