name: .NET Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      working-directory: ./src
      run: dotnet build --configuration Release
      
    - name: Test with dotnet
      working-directory: ./src
      run: dotnet test --configuration Release

    - name: Package NuGet
      working-directory: ./src
      run: dotnet pack --configuration Release

    - name: Upload NuGet
      run: dotnet nuget push ./src/Spice86/bin/Release/Spice86.1.0.0.nupkg
